### ISSUE TITLE
About Me Section

### ISSUE THREAD

**Issue by merzoukfatima** [merzoukfatima/Portfolio#2]
**Description**
Build an About Me section to provide a detailed overview of your background and passion for web development.

**Tasks** 
- [ ] Structure the layout for the About Me section.
- [ ] Write a personal bio.
- [ ] Include details about your education and professional background.
- [ ] Convey your passion for web development.
