### ISSUE TITLE
Showcase Skills

### ISSUE THREAD

**Issue by merzoukfatima** [merzoukfatima/Portfolio#3]
**Description**
Create a section to showcase your technical skills, including programming languages and frameworks.

**Tasks** 
- [ ] Design the layout for the Skills section.
- [ ] List programming languages.
- [ ] Highlight frameworks, libraries, and design/UI/UX skills.
