### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by merzoukfatima** [merzoukfatima/Portfolio#5]
**Description**
Implement a Contact section to facilitate easy communication with visitors.

**Tasks** 
- [ ] Design the layout for the Contact section.
- [ ] Include a contact form or email address.
- [ ] Add links to social media profiles for additional communication channels.
